[project]
name = "movies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "WaffleAtomico", email = "penillaskakievichoscar@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "cassandra-driver>=3.30.1",
]

[project.scripts]
movies = "movies:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
